#!/bin/zsh

#
# Purpose : Start a simple pgAdmin container on port 80.
#
# Usage :
# $> pgadmin
#

docker pull dpage/pgadmin4
docker run -p 80:80 \
    -e 'PGADMIN_DEFAULT_EMAIL=fbuys@duck.com' \
    -e 'PGADMIN_DEFAULT_PASSWORD=password' \
    -d dpage/pgadmin4
